### PR TITLE
Fix cropping of error output when called from another process

### PR DESCRIPTION
**Pull request by jkytomak**
Use similar method as in https://github.com/mochajs/mocha/issues/333

### CODE REVIEW

**Comment by jkytomak** [comment]
Can you please merge this?
We have to use internal fork of jasmine-node, because of this problem.

**Comment by brodybits** [comment]
Will be part of next major release (#436), in order to avoid the possibility of breaking any existing installations.

My apologies for the delay. I picked this up as a maintainer on top of other commitments and may need some more time than may be expected from some more actively supported projects. Some patience on your part would be really appreciated.

It is highly recommended to transition to `jasmine` or `jasmine-npm` if possible.

**Comment by jkytomak** [comment]
Great to hear, thank you for update! Yes, we are moving to `jasmine` or `jasmine-npm` gradually, but we have plenty or repos and own common tools lib so takes a while.

**Comment by jkytomak** [comment]
We are not using jasmine-node anymore, so closing this PR, please resurrect if someone needs it and is able to get tit merged.

**Pull request closed without merging**
