### PR TITLE
[WIP][BETA] Jasmine 2.0 Support

### PR DESCRIPTION
**Pull request by tebriel**
hacking in 2.0 support, pulling out things that are confusing, such as RequireJS support which I'm still not fully convinced ever worked.

you can now install this for testing through npm via:

``` shell
npm install -g jasmine-node@2.0.0-beta4
```

### CODE REVIEW

**Comment by mik01aj** [comment]
I think that you should put a big fat warning that the timer mocking might not work as expected because it mock only `{set,clear}{Interval,Timeout}` functions, and Node has also other scheduling mechanism, `process.nextTick`.

Btw, there is also `setImmediate`, which can work AFAIK both in node and browsers... Maybe it's worth filing an issue for Jasmine itelf. :confused:

**Comment by brodybits** [comment]
Looks like a vote to abandon `Jasmine2.0` version (#437).

**Comment by tebriel** [comment]
I hadn't seen that you added commits to this, was trying to clean up my github.com interface @brodybits. Can re-open the PR if you think it's going to be used, as I hadn't touched it since 2014 I thought it was long-gone.

**Comment by brodybits** [comment]
I would personally rather keep this project in maintenance mode, no new features unless we can get someone else like yourself to help with support and maintenance. Keep in mind that the recommend solution is for users to migrate to `jasmine` or `jasmine-npm`.

**Pull request closed without merging**
